#pragma once
#ifndef __PLAYER_ANIMATION_STATE__
#define __PLAYER_ANIMATION_STATE__

enum class PlayerAnimationState
{
	PLAYER_IDLE_RIGHT,
	PLAYER_IDLE_LEFT,
	PLAYER_IDLE_UP,
	PLAYER_IDLE_DOWN,

	PLAYER_RUN_RIGHT,
	PLAYER_RUN_LEFT,
	PLAYER_RUN_UP,
	PLAYER_RUN_DOWN,

	PLAYER_SWING_RIGHT,
	PLAYER_SWING_LEFT,
	PLAYER_SWING_UP,
	PLAYER_SWING_DOWN,

	NUM_OF_ANIMATION_STATES
};

#endif /* defined (__PLAYER_ANIMATION_STATE__)*/